export const ACTION_UPDATE = 'ACTION_UPDATE';
export const ACTION_SUBMIT = 'ACTION_SUBMIT';
export const ACTION_UPDATE_INPUT_SPEED_1 = 'ACTION_UPDATE_INPUT_SPEED_1';
export const ACTION_UPDATE_INPUT_SPEED_2 = 'ACTION_UPDATE_INPUT_SPEED_2';
export const ACTION_UPDATE_INPUT_TEMP = 'ACTION_UPDATE_INPUT_TEMP';
export const ACTION_UPDATE_PRESET_STATE = 'ACTION_UPDATE_PRESET_STATE';

export const ACTION_GET_PRESETS = 'ACTION_GET_PRESETS';
export const ACTION_GET_PRESETS_SUCCESS = 'ACTION_GET_PRESETS_SUCCESS';
export const ACTION_ADD_PRESET = 'ACTION_ADD_PRESET';
export const ACTION_ADD_PRESET_SUCCESS = 'ACTION_ADD_PRESET_SUCCESS';
export const ACTION_DELETE_PRESET = 'ACTION_DELETE_PRESET';
export const ACTION_DELETE_PRESET_SUCCESS = 'ACTION_DELETE_PRESET_SUCCESS';

export const serverConfig = {
    'host': 'localhost',
    'port': '8080'
}

export const client = {
    'clientId' : 'web-client',
    'port' : '8090'
}