
export enum ActionType {
    ACTION_UPDATE = 'ACTION_UPDATE',
    ACTION_SUBMIT = 'ACTION_SUBMIT',
    ACTION_UPDATE_INPUT_SPEED_1 = 'ACTION_UPDATE_INPUT_SPEED_1',
    ACTION_UPDATE_INPUT_SPEED_2 = 'ACTION_UPDATE_INPUT_SPEED_2',
    ACTION_UPDATE_DIRECTION_INPUT_1 = 'ACTION_UPDATE_DIRECTION_INPUT_1',
    ACTION_UPDATE_DIRECTION_INPUT_2 = 'ACTION_UPDATE_DIRECTION_INPUT_2',
    ACTION_UPDATE_INPUT_TEMP = 'ACTION_UPDATE_INPUT_TEMP',
    ACTION_UPDATE_PRESET_STATE = 'ACTION_UPDATE_PRESET_STATE',
    ACTION_GET_PRESETS = 'ACTION_GET_PRESETS',
    ACTION_GET_PRESETS_SUCCESS = 'ACTION_GET_PRESETS_SUCCESS',
    ACTION_ADD_PRESET = 'ACTION_ADD_PRESET',
    ACTION_ADD_PRESET_SUCCESS = 'ACTION_ADD_PRESET_SUCCESS',
    ACTION_DELETE_PRESET = 'ACTION_DELETE_PRESET',
    ACTION_DELETE_PRESET_SUCCESS = 'ACTION_DELETE_PRESET_SUCCESS',
    ACTION_UPDATE_CONNECTIONS_STATE = 'ACTION_UPDATE_CONNECTIONS_STATE',
    ACTION_GET_ALL_SESSIONS = 'ACTION_GET_ALL_SESSIONS',
    ACTION_GET_ALL_SESSIONS_SUCCESS = 'ACTION_GET_ALL_SESSIONS_SUCCESS',
    ACTION_GET_STATISTICS = 'ACTION_GET_STATISTICS',
    ACTION_GET_STATISTICS_SUCCESS = 'ACTION_GET_STATISTICS_SUCCESS',
    ACTION_GET_SETTINGS = 'ACTION_GET_SETTINGS',
    ACTION_GET_SETTINGS_SUCCESS = 'ACTION_GET_SETTINGS_SUCCESS',
    ACTION_SUBMIT_SETTINGS = 'ACTION_SUBMIT_SETTINGS',
    ACTION_CHANGE_HARDWARE_CONNECTION = 'ACTION_CHANGE_HARDWARE_CONNECTION',
    ACTION_UPDATE_ELONGATION_STATUS = 'ACTION_UPDATE_ELONGATION_STATUS',
    ACTION_UPDATE_REEL_DIAMETER = 'ACTION_UPDATE_REEL_DIAMETER',
    ACTION_SUBMIT_REEL_DIAMETER = 'ACTION_SUBMIT_REEL_DIAMETER', 
    ACTION_SUBMIT_AUTO_PROGRAM = 'ACTION_SUBMIT_AUTO_PROGRAM',
    ACTION_UPDATE_AUTO_PROGRAM = 'ACTION_UPDATE_AUTO_PROGRAM',
    ACTION_TOGGLE_AUTO_PROGRAM_REQUEST = 'ACTION_TOGGLE_AUTO_PROGRAM_REQUEST' ,
    ACTION_TOGGLE_AUTO_PROGRAM = 'ACTION_TOGGLE_AUTO_PROGRAM'
} 

export const serverConfig = {
    'host': 'localhost',
    'port': '8080'
}

export const client = {
    'clientId' : 'web-client',
    'port' : '8090'
}